"""empty message

Revision ID: 747381d711de
Revises: bbf7cc608867
Create Date: 2023-09-19 13:26:44.988958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '747381d711de'
down_revision = 'bbf7cc608867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('list_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'todolists', ['list_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('list_id')

    # ### end Alembic commands ###
