"""empty message

Revision ID: 789c0b300ab5
Revises: d7e31cef944c
Create Date: 2023-09-19 17:51:55.850494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789c0b300ab5'
down_revision = 'd7e31cef944c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todolists', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todolists', schema=None) as batch_op:
        batch_op.alter_column('completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
