"""empty message

Revision ID: 842dd798cab5
Revises: 747381d711de
Create Date: 2023-09-19 13:33:52.109832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842dd798cab5'
down_revision = '747381d711de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('list_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.alter_column('list_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
