"""empty message

Revision ID: bbf7cc608867
Revises: 37b6ad030d5a
Create Date: 2023-09-03 21:57:51.246340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbf7cc608867'
down_revision = '37b6ad030d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), nullable=True))
        batch_op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
        batch_op.alter_column('todos','completed', nullable =False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todos', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
